version: '3.9'
services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    volumes:
      - mongo:/data/db
    env_file:
      - .env.dev
    ports:
      - '27017:27017'
  backend:
    container_name: message-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env.dev
  
volumes:
  mongo:
    name: message-mongo
