FROM node:18 AS builder

RUN npm install -g pnpm

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN pnpm install

COPY . .

RUN pnpm build

FROM node:18

RUN npm install -g pnpm

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/pnpm-lock.yaml ./
COPY --from=builder /app/dist ./dist

COPY --from=builder /app/prisma ./prisma

EXPOSE 3000
CMD [ "pnpm", "start:migrate:dev" ]