version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env.local
    ports:
      - '5432:5432'
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.dev
volumes:
  postgres:
    name: message-db
